"""role_groups_store_id_to_store_ids

Revision ID: 73f7f59a9c8a
Revises: fa1a6af895fb
Create Date: 2026-06-06 12:24:49.653230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f7f59a9c8a'
down_revision: Union[str, None] = 'fa1a6af895fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('role_groups', sa.Column('store_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False))
    # Migrate: wrap existing single store_id into the new array
    op.execute("UPDATE role_groups SET store_ids = ARRAY[store_id]::uuid[] WHERE store_id IS NOT NULL")
    op.drop_constraint(op.f('role_groups_store_id_fkey'), 'role_groups', type_='foreignkey')
    op.drop_column('role_groups', 'store_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_groups', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('role_groups_store_id_fkey'), 'role_groups', 'stores', ['store_id'], ['id'])
    op.drop_column('role_groups', 'store_ids')
    # ### end Alembic commands ###
